// GENERATED by tools/refresh_prices.py — do not edit by hand.
//
// Coverage summary for the committed price history, surfaced on the
// Info tab (the full dataset lives in data/prices_history.json).

const int kPriceFundCount = 100;
const int kPriceCloseCount = 72417;
const String kPriceEarliest = '2007-12-27';
