// GENERATED by tools/refresh_roc.py — do not edit by hand.
//
// Trailing return-of-capital % per YieldMax fund, aggregated from their
// Section 19a-1 notices (ROC $ / total $ over the sampled weeks). These
// are estimates; rerun the script to refresh. See the project-roc-autofetch
// memory for the source/approach.
//
// As of: 2025-12-19

const String kRocDataAsOf = '2025-12-19';

/// Ticker -> trailing return-of-capital %, used to auto-fill the ROC field
/// when a known YieldMax fund is entered.
const Map<String, double> kRocByTicker = {
  'ABNY': 70.1,
  'AIYY': 77.4,
  'AMDY': 38.2,
  'AMZY': 32.4,
  'APLY': 36.6,
  'BRKC': 33.1,
  'CONY': 43.4,
  'CRCO': 88.7,
  'CRSH': 29.1,
  'CVNY': 34.2,
  'DIPS': 22.6,
  'DISO': 41.9,
  'DRAY': 81.8,
  'FBY': 60.1,
  'FIAT': 36.0,
  'GDXY': 63.1,
  'GMEY': 56.7,
  'GOOY': 64.7,
  'HIYY': 59.1,
  'HOOY': 48.5,
  'JPMO': 31.1,
  'MARO': 46.0,
  'MRNY': 80.1,
  'MSTY': 83.5,
  'NFLY': 9.1,
  'NVDY': 18.0,
  'OARK': 48.2,
  'PLTY': 41.4,
  'PYPY': 61.2,
  'RBLY': 71.8,
  'RDYY': 64.1,
  'SMCY': 12.0,
  'SNOY': 40.4,
  'TSLY': 23.4,
  'TSMY': 25.4,
  'WNTR': 58.3,
  'XOMO': 51.6,
  'XYZY': 50.4,
  'YMAG': 71.0,
  'YMAX': 71.0,
  'YQQQ': 49.3,
};
